# Generated by Django 3.2.4 on 2021-06-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccination_Officer',
        ),
    ]
