# Generated by Django 3.2.4 on 2021-06-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0002_delete_vaccination_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint_queue',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
