# Generated by Django 3.2.4 on 2021-06-25 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1', models.IntegerField(blank=True, null=True)),
                ('d2', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint_Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vans.van')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vans.waypoint')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vans.van')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vans.waypoint')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination_Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vans.van')),
            ],
        ),
    ]
